/**
 * Role discriminant for {@link ChatEntry} - the same four values
 * `hal-engine` discriminates `SessionEntry` on (docs/websocket-protocol.md §6).
 */
export type ChatEntryRole = "user" | "assistant" | "thinking" | "tool";

/**
 * A message authored by the user (docs/websocket-protocol.md §6.1).
 * Fully formed on arrival - it never streams (§7.2).
 */
export interface UserChatEntry {
  /** Opaque identifier assigned by the consuming adapter. */
  id: string;
  /** Discriminant. */
  role: "user";
  /** The message text. */
  content: string;
}

/**
 * A response generated by the AI model (docs/websocket-protocol.md §6.2).
 * Streams via the upsert/delta/commit lifecycle (§7.1).
 */
export interface AssistantChatEntry {
  /** Opaque identifier assigned by the consuming adapter. */
  id: string;
  /** Discriminant. */
  role: "assistant";
  /** Markdown text, grown incrementally while streaming. */
  content: string;
  /** `true` while deltas are still arriving; `false` once committed. */
  isStreaming: boolean;
  /**
   * Presentational status line shown while a tool runs (for example
   * "Running get_weather..."). Caller-supplied: this field has no
   * counterpart anywhere in the HAL protocol.
   */
  toolStatus?: string;
  /**
   * Which persona answered, as an opaque identifier the caller supplies -
   * the counterpart to `hal-engine`'s `AssistantEntry.persona`. The package
   * never resolves it: it is a key into the consumer's own `attribution`
   * lookup (see `ChatAttribution`), never rendered and never interpreted
   * here. It must not carry personal data - it is persisted, replayed and
   * logged wherever the session is (docs/design-notes.md § Attribution).
   */
  persona?: string;
}

/**
 * Internal AI reasoning, rendered as a collapsible section
 * (docs/websocket-protocol.md §6.3). Streams via the
 * upsert/delta/commit lifecycle (§7.1).
 */
export interface ThinkingChatEntry {
  /** Opaque identifier assigned by the consuming adapter. */
  id: string;
  /** Discriminant. */
  role: "thinking";
  /** Reasoning text, grown incrementally while streaming. */
  content: string;
  /** `true` while deltas are still arriving; `false` once committed. */
  isStreaming: boolean;
}

/**
 * A tool invocation requested by the AI model
 * (docs/websocket-protocol.md §6.4). Fully formed on arrival (§7.2)
 * and carries no `content`.
 */
export interface ToolChatEntry {
  /** Opaque identifier assigned by the consuming adapter. */
  id: string;
  /** Discriminant. */
  role: "tool";
  /** Registered tool name. */
  toolName: string;
  /** Key-value pairs passed to the tool. */
  toolInput: Record<string, unknown>;
}

/**
 * The view model bowman-ui components render: one entry per piece of
 * conversation content, discriminated on `role`. Designed against
 * `hal-engine` docs/websocket-protocol.md §6 (SessionEntry Objects),
 * read at commit 0fb475caae1dc3c07948911faf4c16510e263f88. Entries
 * carry an opaque `id` supplied by the consuming adapter - never a
 * protocol index - and drop the protocol's `timestamp`. bowman-ui says
 * nothing about transport: the adapter that turns protocol events into
 * these entries lives in the consuming app.
 */
export type ChatEntry = UserChatEntry | AssistantChatEntry | ThinkingChatEntry | ToolChatEntry;

/**
 * Coarse conversation state a chat surface renders: `"idle"` between
 * exchanges, `"streaming"` while a response is in flight, `"error"`
 * after a terminal protocol error.
 */
export type ChatStreamState = "idle" | "streaming" | "error";

/**
 * Error details a chat surface renders. `code` is the machine-readable
 * code from the protocol's error message; HAL sends `INVALID_MESSAGE`,
 * `INVALID_FORMAT`, `RATE_LIMITED` or `SERVER_ERROR`
 * (docs/websocket-protocol.md §5.6), but the field stays an open
 * string so new codes render without a type change.
 */
export interface ChatErrorInfo {
  /** Human-readable detail. */
  message: string;
  /** Machine-readable code, when the source provides one. */
  code?: string;
}
